'------------------------------------------------------------------------------
' <auto-generated>
'     這段程式碼是由工具產生的。
'     執行階段版本:4.0.30319.18034
'
'     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
'     變更將會遺失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System.Runtime.Serialization

Namespace CompanyWebDBChange
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="DBServerNameEnum", [Namespace]:="http://tempuri.org/")>  _
    Public Enum DBServerNameEnum As Integer
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        MainDBServer = 0
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        BackupDBServer1 = 1
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        BackupDBServer2 = 2
    End Enum
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="CompanyWebDBChange.DBServerChangeSoap")>  _
    Public Interface DBServerChangeSoap
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/SetDBConnect", ReplyAction:="*")>  _
        Function SetDBConnect(ByVal SetServer As CompanyWebDBChange.DBServerNameEnum) As Boolean
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface DBServerChangeSoapChannel
        Inherits CompanyWebDBChange.DBServerChangeSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class DBServerChangeSoapClient
        Inherits System.ServiceModel.ClientBase(Of CompanyWebDBChange.DBServerChangeSoap)
        Implements CompanyWebDBChange.DBServerChangeSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function SetDBConnect(ByVal SetServer As CompanyWebDBChange.DBServerNameEnum) As Boolean Implements CompanyWebDBChange.DBServerChangeSoap.SetDBConnect
            Return MyBase.Channel.SetDBConnect(SetServer)
        End Function
    End Class
End Namespace
