'------------------------------------------------------------------------------
' <auto-generated>
'     這段程式碼是由工具產生的。
'     執行階段版本:4.0.30319.17929
'
'     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
'     變更將會遺失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Data
Imports System.Data.Linq
Imports System.Data.Linq.Mapping
Imports System.Linq
Imports System.Linq.Expressions
Imports System.Reflection


<Global.System.Data.Linq.Mapping.DatabaseAttribute(Name:="QCdb01")>  _
Partial Public Class Qcdb01DataContext
	Inherits System.Data.Linq.DataContext
	
	Private Shared mappingSource As System.Data.Linq.Mapping.MappingSource = New AttributeMappingSource()
	
  #Region "擴充性方法定義"
  Partial Private Sub OnCreated()
  End Sub
  Partial Private Sub InsertMailMsgEdit(instance As MailMsgEdit)
    End Sub
  Partial Private Sub UpdateMailMsgEdit(instance As MailMsgEdit)
    End Sub
  Partial Private Sub DeleteMailMsgEdit(instance As MailMsgEdit)
    End Sub
  #End Region
	
	Public Sub New()
        MyBase.New(Global.CompanyLINQDB.My.MySettings.Default.Server1_QCdb01, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public ReadOnly Property MailMsgEdit() As System.Data.Linq.Table(Of MailMsgEdit)
		Get
			Return Me.GetTable(Of MailMsgEdit)
		End Get
	End Property
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.MailMsgEdit")>  _
Partial Public Class MailMsgEdit
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _ID As String
	
	Private _MailType As Integer
	
	Private _ReceivePersonName As String
	
	Private _MailAddress As String
	
    #Region "擴充性方法定義"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnIDChanging(value As String)
    End Sub
    Partial Private Sub OnIDChanged()
    End Sub
    Partial Private Sub OnMailTypeChanging(value As Integer)
    End Sub
    Partial Private Sub OnMailTypeChanged()
    End Sub
    Partial Private Sub OnReceivePersonNameChanging(value As String)
    End Sub
    Partial Private Sub OnReceivePersonNameChanged()
    End Sub
    Partial Private Sub OnMailAddressChanging(value As String)
    End Sub
    Partial Private Sub OnMailAddressChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ID", DbType:="NChar(38) NOT NULL", CanBeNull:=false, IsPrimaryKey:=true)>  _
	Public Property ID() As String
		Get
			Return Me._ID
		End Get
		Set
			If (String.Equals(Me._ID, value) = false) Then
				Me.OnIDChanging(value)
				Me.SendPropertyChanging
				Me._ID = value
				Me.SendPropertyChanged("ID")
				Me.OnIDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_MailType", DbType:="Int NOT NULL")>  _
	Public Property MailType() As Integer
		Get
			Return Me._MailType
		End Get
		Set
			If ((Me._MailType = value)  _
						= false) Then
				Me.OnMailTypeChanging(value)
				Me.SendPropertyChanging
				Me._MailType = value
				Me.SendPropertyChanged("MailType")
				Me.OnMailTypeChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ReceivePersonName", DbType:="NChar(20)")>  _
	Public Property ReceivePersonName() As String
		Get
			Return Me._ReceivePersonName
		End Get
		Set
			If (String.Equals(Me._ReceivePersonName, value) = false) Then
				Me.OnReceivePersonNameChanging(value)
				Me.SendPropertyChanging
				Me._ReceivePersonName = value
				Me.SendPropertyChanged("ReceivePersonName")
				Me.OnReceivePersonNameChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_MailAddress", DbType:="NChar(50) NOT NULL", CanBeNull:=false)>  _
	Public Property MailAddress() As String
		Get
			Return Me._MailAddress
		End Get
		Set
			If (String.Equals(Me._MailAddress, value) = false) Then
				Me.OnMailAddressChanging(value)
				Me.SendPropertyChanging
				Me._MailAddress = value
				Me.SendPropertyChanged("MailAddress")
				Me.OnMailAddressChanged
			End If
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
End Class
